hydra:
    run:
        dir: /kqi/output/fold_${dataset.fold}

dataset: 
    data_dir: /kqi/parent
    fold: 1

trainer:
    distributed_backend: dp
    precision: 16
    batch_size: 8
    image_size: 2048
    num_sanity_val_steps: 5

model:
    class_name: model.model.se_resnet50
    params: {num_classes: 6, pool: avg, pool_size: 1, pretrained: /kqi/input/training/22466428/se_resnet50-ce0d4300.pth}

training:
    loss:
        class_name: torch.nn.CrossEntropyLoss
    y2pred: argmax

