hydra:
    run:
        dir: /kqi/output/fold_${dataset.fold}

model:
    class_name: timm.create_model
    params: {model_name: gluon_seresnext50_32x4d, num_classes: 1, pretrained: true}

dataset: 
    data_dir: /kqi/parent
    fold: 1
    target_type: float # long
    image_size: 2048
    load_type: tiff_tile
    layer: 1
    split:
        params: {n_splits: 10, shuffle: true, random_state: 2020}

training:
    loss: 
        class_name: losses.loss.RMSELoss
        params: {}
    optimizer:
        class_name: torch.optim.SGD
        params: {lr: 1e-2}
    scheduler:
        class_name: torch.optim.lr_scheduler.CyclicLR
        params: {base_lr: 1e-3, max_lr: 1e-2, mode: triangular, gamma: 0.99997, cycle_momentum: true, step_size_up: 5, step_size_down: 10} 
        interval: epoch

    dataloader:
        train: {batch_size: '${training.batch_size}', shuffle: true, num_workers: 4, pin_memory: true, drop_last: false}    
        valid: {batch_size: '${training.batch_size}', shuffle: false, num_workers: 4, pin_memory: true, drop_last: false} 
    batch_size: 8

trainer:
    distributed_backend: dp
    precision: 16
    num_sanity_val_steps: 5