hydra:
    run:
        dir: /kqi/output/fold_${dataset.fold}

dataset: 
    data_dir: /kqi/parent
    fold: 1
    target_type: float # long
    image_size: 2048
    load_type: tiff_tile
    layer: 1
    cleansing: null

    split:
        params: {n_splits: 10, shuffle: true, random_state: 2020}

trainer:
    distributed_backend: dp
    precision: 16
    num_sanity_val_steps: 5
    min_epochs: 400
    max_epochs: 400

model:
    ckpt_path: null
    class_name: model.model.timm_custom
    params: {model_name: gluon_seresnext50_32x4d, num_classes: 1, pretrained: true, pool_size: 1, pool_type: avgmax, head_type: custom}

training:
    loss:
        class_name: torch.nn.SmoothL1Loss #losses.loss.RMSELoss
    y2pred: round
    scheduler:
        class_name: scheduler.scheduler.CyclicLR
        params: {base_lr: 5e-6, max_lr: 1e-4, mode: exp_range, gamma: 0.99998, cycle_momentum: false} 
        interval: step
    optimizer:
        class_name: torch.optim.Adam
        params: {lr: 1e-4}
    batch_size: 8

