hydra:
    run:
        dir: /kqi/output/fold_${dataset.fold}

dataset: 
    data_dir: /kqi/parent
    fold: 1
    target_type: float # long
    image_size: 2048
    load_type: tiff_tile
    layer: 1
    split:
        params: 
            n_splits: 10

trainer:
    distributed_backend: dp
    precision: 16
    num_sanity_val_steps: 5

model:
    class_name: model.model.se_resnet50
    params: {num_classes: 1, pool: gem, pool_size: 1, pretrained: null}

training:
    loss:
        class_name: losses.loss.RMSELoss
    y2pred: round
    scheduler:
        class_name: scheduler.scheduler.CyclicLR
        params: {base_lr: 0.005, max_lr: 0.1, mode: exp_range, gamma: 0.99994} 
        interval: step
    optimizer:
        class_name: torch.optim.SGD
        params: {lr: 0.1}
    batch_size: 8

