general:
    project_name: wheat
    save_dir: logs/
    workspace: erlemar
logging:
    log: true
private:
    neptune_api: ANONIMOUS
model:
    backbone:
        class_name: model.model.resnet18
        params:
            pretrained: true
            num_classes: 1
dataset: 
    data_dir: ../data
    split:
        class_name: sklearn.model_selection.StratifiedKFold
        params: 
            n_splits: 5
            shuffle: True
            random_state: 2020
    fold: 0
    augmentation:
        train:
            - class_name: albumentations.RandomResizedCrop
              params: {height: 2048, width: 2048, scale: [0.8, 1.0], ratio: [1, 1], interpolation: 1, always_apply: False, p: 1.0}
            - class_name: albumentations.Flip
              params: {always_apply: False, p: 0.5}
            - class_name: albumentations.RandomGridShuffle
              params: {grid: [4, 4], always_apply: False, p: 1.0}
            - class_name: albumentations.HueSaturationValue
              params: {hue_shift_limit: 10, sat_shift_limit: 10, val_shift_limit: 10, always_apply: False, p: 0.5}
            - class_name: albumentations.RandomBrightnessContrast
              params: {brightness_limit: 0.2, contrast_limit: 0.2, brightness_by_max: True, always_apply: False, p: 0.5}
            - class_name: albumentations.GaussNoise
              params: {var_limit: [10.0, 50.0], mean: 0, always_apply: False, p: 0.5}
            - class_name: albumentations.ShiftScaleRotate
              params: {shift_limit: 0.0625, scale_limit: 0.0, rotate_limit: 45, interpolation: 1, border_mode: 4, value: 255, mask_value: None, always_apply: False, p: 0.5}
            - class_name: albumentations.Normalize
              params: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], max_pixel_value: 255.0, always_apply: False, p: 1.0}
            - class_name: albumentations.Cutout
              params: {num_holes: 8, max_h_size: 8, max_w_size: 8, fill_value: 0, always_apply: False, p: 0.5}
        valid: 
            - class_name: albumentations.Resize
              params: {height: 2048, width: 2048, interpolation: 1, always_apply: False, p: 1.0}
            - class_name: albumentations.Normalize
              params: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], max_pixel_value: 255.0, always_apply: False, p: 1.0}


training:
    debug: False